name: api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.13
  dart_frog: ^1.0.0
  dio: ^5.7.0
  dotenv: ^4.2.0
  equatable: ^2.0.5
  intl: ^0.20.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  stormberry: ^0.14.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
